const fs=require('fs'),vm=require('vm'),THREE=require('../assets/three.min.js');
const nodes={};function node(){return {children:[],style:{},dataset:{},classList:{toggle(){},remove(){},add(){}},appendChild(b){this.children.push(b)},querySelectorAll(){return this.children},addEventListener(){},getBoundingClientRect(){return {width:1200,height:800}},getContext(){return new Proxy({},{get:()=>()=>{}})}}};THREE.WebGLRenderer=class{constructor(){this.domElement=node();this.shadowMap={}}setPixelRatio(){}setSize(){}render(){}};
Object.assign(global,{THREE,window:global,addEventListener:()=>{},document:{getElementById:id=>nodes[id]||(nodes[id]=node()),createElement:()=>node(),querySelectorAll:()=>[],querySelector:()=>node(),addEventListener:()=>{},documentElement:{}},matchMedia:()=>({matches:false}),innerWidth:1200,devicePixelRatio:1,ResizeObserver:class{observe(){}},requestAnimationFrame:()=>{}});
for(let n=1;n<=5;n++){
let code=fs.readFileSync(`app${n}.js`,'utf8').replace('window.tourModel={','window.exportParts={world,walls,ceiling,W,D};window.tourModel={');vm.runInThisContext(code);const m=global.tourModel,e=global.exportParts;if(!m)throw Error('No scene '+n);m.scene.updateMatrixWorld(true);const polygons=[],excluded=new Set([m.roof,m.exterior,e.ceiling]);
function walk(o){if(excluded.has(o))return;if(o.isMesh&&o.geometry){let b=new THREE.Box3().setFromObject(o),min=b.min,max=b.max,k=m.scale;if(min.y>=2.15||max.y<-.08||max.x-min.x>20*k||max.z-min.z>20*k||min.x<-.4*k||max.x>(e.W+.5)*k||max.z>(e.D+.4)*k||min.z<-3.2*k)return;
const isWall=e.walls.includes(o)&&max.y>2.5&&min.y<.1;let color=isWall?'#303945':e.walls.includes(o)?'#d5e6eb':'#'+(o.material.color?.getHexString()||'dddddd');const pos=o.geometry.attributes.position,pts=[];for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld);pts.push([v.x/k,v.z/k]);}pts.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);let lo=[],hi=[];for(const p of pts){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),p)<=0)lo.pop();lo.push(p);}for(const p of pts.slice().reverse()){while(hi.length>=2&&cross(hi.at(-2),hi.at(-1),p)<=0)hi.pop();hi.push(p);}lo.pop();hi.pop();const hull=lo.concat(hi);if(hull.length>=3)polygons.push({points:hull,color,y:max.y,wall:isWall});
}else for(const ch of o.children)walk(ch);}
walk(e.world);if(n===2)for(const o of m.exterior.children){const b=new THREE.Box3().setFromObject(o),k=m.scale;if(b.min.x>=0&&b.max.x<=e.W*k&&b.min.z>=-3*k&&b.max.z<0&&b.max.y<2.15)walk(o);}polygons.sort((a,b)=>(a.wall?10:a.y)-(b.wall?10:b.y));const rooms=m.rooms.map(r=>({...r,area:(r.cells||[r]).reduce((v,c)=>v+c.w*c.d,0)*m.scale*m.scale}));fs.writeFileSync(`scene${n}.json`,JSON.stringify({W:e.W,D:e.D,scale:m.scale,rooms,polygons}));console.log(n,polygons.length,rooms.reduce((a,r)=>a+r.area,0));}
